# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-17 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeSnippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=2000)),
                ('title', models.CharField(max_length=256)),
                ('languages', models.CharField(choices=[('JA', 'Java'), ('JS', 'Javascript'), ('PY', 'Python'), ('HT', 'HTML')], default='PY', max_length=2)),
            ],
        ),
    ]
